server:
  port: 8082

spring:
  application:
    name: debezium-demo
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/productsdb
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: false
        schema.registry.url: http://localhost:8081
      auto-offset-reset: earliest
      enable-auto-commit: true

